export const AuthAction = {
    GET_USER_SUCCESS:"GET_USER_SUCCESS",
    GET_USER_FAIL:"GET_USER_FAIL",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
    PROFILE_UPDATE_FAIL: "PROFILE_UPDATE_FAIL",
};