export const ChatActionTypes = {
    GET_INIT_CHAT_ROOMS_SUCCESS :"GET_INIT_CHAT_ROOMS_SUCCESS",
    GET_INIT_CHAT_ROOMS_FAILS :"GET_INIT_CHAT_ROOMS_FAILS",
    GET_NEW_MESSAGE:"GET_NEW_MESSAGE",
    FIRST_MESSAGE_INIT_CHAT:"FIRST_MESSAGE_INIT_CHAT"
}