export const ProfileAction = {
    GET_SUBSECTION_DATA_SUCCESS:"GET_SUBSECTION_DATA_SUCCESS",
    GET_SUBSECTION_DATA_FAILS:"GET_SUBSECTION_DATA_FAILS",
    LOAD_MORE_SUBSECTION_DATA_SUCCESS:"LOAD_MORE_SUBSECTION_DATA_SUCCESS",
    LOAD_MORE_SUBSECTION_DATA_FAILS:"LOAD_MORE_SUBSECTION_DATA_FAILS",
    GET_NOTIFICATION_DATA_SUCCESS:"GET_NOTIFICATION_DATA_SUCCESS",
    GET_NOTIFICATION_DATA_FAILS:"GET_NOTIFICATION_DATA_FAILS",
    REMOVE_PROFILE_STATE_DATA:"REMOVE_PROFILE_STATE_DATA",
    REMOVE_NOTIFICATION_STATE_DATA:"REMOVE_NOTIFICATION_STATE_DATA",
}