export const ProfileAction = {
    GET_SUBSECTION_DATA_SUCCESS:"GET_SUBSECTION_DATA_SUCCESS",
    GET_SUBSECTION_DATA_FAILS:"GET_SUBSECTION_DATA_FAILS",
    LOAD_MORE_SUBSECTION_DATA_SUCCESS:"LOAD_MORE_SUBSECTION_DATA_SUCCESS",
    LOAD_MORE_SUBSECTION_DATA_FAILS:"LOAD_MORE_SUBSECTION_DATA_FAILS"

}