export const PropertiesActionTypes = {
    GET_PROPERTY_DATA_SUCCESS:"GET_PROPERTY_DATA_SUCCESS",
    GET_PROPERTY_DATA_FAILS:"GET_PROPERTY_DATA_FAILS",

    // for saved homes screen
    GET_SAVED_HOMES_DATA_SUCCESS:"GET_SAVED_HOMES_DATA_SUCCESS",
    GET_SAVED_HOMES_DATA_FAILS:"GET_SAVED_HOMES_DATA_FAILS",
    REMOVE_SAVED_HOMES_DATA:"REMOVE_SAVED_HOMES_DATA"
}