export const SingleHomeAction = {
    GET_HOME_DATA_SUCCESS:"GET_HOME_DATA_SUCCESS",
    GET_HOME_DATA_FAILS:"GET_HOME_DATA_FAILS",
    REMOVE_HOME_DATA:"REMOVE_HOME_DATA",
    GET_OTHERS_HOME_DATA_SUCCESS:"GET_OTHERS_HOME_DATA_SUCCESS",
    GET_OTHERS_HOME_DATA_FAILS : "GET_OTHERS_HOME_DATA_FAILS",
    REMOVE_OTHERS_HOME_DATA:"REMOVE_OTHERS_HOME_DATA",
    SAVE_HOME_SUCCESS:"SAVE_HOME_SUCCESS",
    SAVE_HOME_FAILS:"SAVE_HOME_FAILS",
    REMOVE_SAVE_HOME_SUCCESS:"REMOVE_SAVE_HOME_SUCCESS",
    REMOVE_SAVE_HOME_FAILS:"REMOVE_SAVE_HOME_FAILS"
}